import pandas as pd

# Read the enhanced results
df = pd.read_csv(r'G:\My Drive\Hirejoure.com\Instrumentation_and_Measurement_Execs v2 - ENRICHED.csv')

print('Bureau Veritas emails generated by our script:')
print('=' * 60)

# Find Bureau Veritas employees
bv_emails = df[df['domain'].str.contains('bureauveritas', na=False)]

for _, row in bv_emails.iterrows():
    print(f'{row["first_name"]:15} {row["last_name"]:15} -> {row["email"]}')

print(f'\nTotal Bureau Veritas emails: {len(bv_emails)}')
print('\nPROBLEM: All emails use first.last@bureauveritas.com pattern')
print('This is just an ASSUMPTION - not verified with Google or external APIs!')
print('\nThe script should check:')
print('- Google search results for actual email formats')
print('- Hunter.io or similar services for verified patterns')
print('- LinkedIn profiles for actual email addresses')
print('- Company directories or contact pages')
